config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root to: 'home#index'

  get 'press', to: 'press#index'
  get 'tr', to: 'tr#index'
  get 'admin', to: 'admin#index'
  get 'employment', to: 'employment#index'
  get 'order', to: 'order#index'
  get 'blog', to: 'blog#index'

  get '/payment', to: redirect('http://tinyurl.com/cheese-invoice')

  get 'logout',
      controller: 'sessions',
      action: 'destroy'

  match 'login', via: [:get, :post],
                 controller: 'sessions',
                 action: 'new'

  %w[404 422 500].each do |code|
    get code, to: 'errors#show', code: code
  end

  resources :articles
  resources :sessions
  resources :products
  resources :accounts

  namespace :user do
    resources :orders
    resources :contacts
    resources :users
  end

  namespace :admin do
    get 'fulfillment', to: 'fulfillment#index'
    resources :salespeople
    resources :states
    resources :towns
    resources :distributors
    resources :distribution_centers
    resources :trade_items
    resources :users do
      member do
        get 'undestroy'
      end
    end
    resources :articles
    resources :products
    resources :notes
    resources :reports do
      collection do
        get 'sales_activity'
      end
    end
    resources :contacts do
      member do
        get 'undestroy'
        get 'repeat_last_order'
      end
    end
    resources :orders do
      member do
        get 'fulfill'
        get 'unfulfill'
        get 'invoice'
        get 'update_invoice'
      end
    end
  end
end

app/views/admin/index.html.erb
<h1>Administration</h1>

<div class="c_panel">
  <fieldset>
    <legend><%= link_to "Orders", admin_orders_path %></legend>
    <ul>
      <li>
        <%= link_to "New Order", new_admin_order_path %>
      </li>
      <% unless @late_orders.size == 0 -%>
        <li class="urgent">
          <%= orders_link @late_orders, "late", {show: :late} %>
        </li>
      <% end -%>
      <li>
        <%= orders_link @todays_orders, "to fulfill today" %>
      </li>
      <li>
        <%= orders_link @orders, "in total" %>
      </li>
    </ul>
  </fieldset>

  <fieldset>
    <legend><%= link_to "Contacts", admin_contacts_path %></legend>
    <ul>
      <li>
        <%= link_to 'New Contact', new_admin_contact_path %>
      </li>
      <% unless @urgent_contacts.size == 0 -%>
        <li class="urgent">
          <%= contacts_link @urgent_contacts, "", {show: :urgent} %>
        </li>
      <% end -%>
      <li>
        <%= pluralize @contacts, 'contact' %>
      </li>
    </ul>
  </fieldset>

  <fieldset>
    <legend><%= link_to "News", admin_articles_path %></legend>
    <ul>
      <li>
        <%= link_to 'New Article', new_admin_article_path %>
      </li>
      <li>
        <%= pluralize @articles, 'article' %>
      </li>
    </ul>
  </fieldset>

  <fieldset>
    <legend><%= link_to "Products", admin_products_path %></legend>
    <ul>
      <li>
        <%= link_to 'New Product', new_admin_product_path %>
      </li>
      <li>
        <%= pluralize @products, 'product' %>
      </li>
      <li>
        <%= pluralize @active_products, 'product' %> in production
      </li>
    </ul>
  </fieldset>

  <fieldset>
    <legend><%= link_to "Reports", admin_reports_path %></legend>
    <ul>
      <li>
        <%= link_to 'Sales Activity', sales_activity_admin_reports_path %>
      </li>
      <li>
        <%= link_to 'New Report', new_admin_report_path %>
      </li>
      <li>
        <%= pluralize @reports, 'Report' %>
      </li>
    </ul>
  </fieldset>

  <fieldset>
    <legend><%= link_to "Locations", admin_states_path %></legend>
    <ul>
      <li>
        <%= link_to 'New State', new_admin_state_path %>
      </li>
      <li>
        <%= pluralize @states, 'State' %>
      </li>
      <li>
        <%= link_to 'New Town', new_admin_town_path %>
      </li>
      <li>
        <%= pluralize @towns, 'Town' %>
      </li>
    </ul>
  </fieldset>

  <fieldset>
    <legend><%= link_to "DCs", admin_distribution_centers_path %></legend>
    <ul>
      <li>
        <%= link_to 'New Distribution Center', new_admin_distribution_center_path %>
      </li>
      <li>
        <%= pluralize @distribution_centers, 'DC' %>
      </li>
    </ul>
  </fieldset>

  <fieldset>
    <legend><%= link_to "Salespeople", admin_salespeople_path %></legend>
    <ul>
      <li>
        <%= link_to 'New Salesperson', new_admin_salesperson_path %>
      </li>
      <li>
        <%= pluralize @salespeople, 'salesperson' %>
      </li>
    </ul>
  </fieldset>
</div>