config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root to: 'home#index'

  get 'press', to: 'press#index'
  get 'tr', to: 'tr#index'
  get 'admin', to: 'admin#index'
  get 'employment', to: 'employment#index'
  get 'order', to: 'order#index'
  get 'blog', to: 'blog#index'

  get '/payment', to: redirect('http://tinyurl.com/cheese-invoice')

  get 'logout',
      controller: 'sessions',
      action: 'destroy'

  match 'login', via: [:get, :post],
                 controller: 'sessions',
                 action: 'new'

  %w[404 422 500].each do |code|
    get code, to: 'errors#show', code: code
  end

  resources :articles
  resources :sessions
  resources :products
  resources :accounts

  namespace :user do
    resources :orders
    resources :contacts
    resources :users
  end

  namespace :admin do
    get 'fulfillment', to: 'fulfillment#index'
    resources :salespeople
    resources :states
    resources :towns
    resources :distributors
    resources :distribution_centers
    resources :trade_items
    resources :users do
      member do
        get 'undestroy'
      end
    end
    resources :articles
    resources :products
    resources :notes
    resources :reports do
      collection do
        get 'sales_activity'
      end
    end
    resources :contacts do
      member do
        get 'undestroy'
        get 'repeat_last_order'
      end
    end
    resources :orders do
      member do
        get 'fulfill'
        get 'unfulfill'
        get 'invoice'
        get 'update_invoice'
      end
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :contact
  has_many :line_items, dependent: :destroy, inverse_of: :order
  belongs_to :created_by, class_name: 'User'
  belongs_to :updated_by, class_name: 'User'
  accepts_nested_attributes_for :line_items,
                                reject_if: proc { |attributes| attributes['units'].blank? },
                                allow_destroy: true

  validates_presence_of :contact_id, :delivery_date

  scope :late, lambda {
    where('fulfilled_on is null and delivery_date < ?', Date.today).order('delivery_date asc')
  }

  scope :fulfilled, -> { where('fulfilled_on is not null').order('fulfilled_on DESC') }

  scope :active, -> { where(fulfilled_on: nil).order('delivery_date asc') }

  def self.to_be_fulfilled(day)
    if day == Date.today
      Order.where('fulfilled_on is NULL AND delivery_date <= ?', Date.today)
    else
      Order.where(fulfilled_on: nil, delivery_date: day)
    end
  end

  def self.display_all(show)
    display(Order.all, show)
  end

  def self.display(orders, show)
    case show
    when 'late'
      [orders.late, 'Late Orders']
    when 'fulfilled'
      [orders.fulfilled, 'Delivered Orders']
    when 'active'
      [orders.active, 'Active Orders']
    else
      contact = Contact.find_by_id(show)
      [contact.orders.order('delivery_date DESC'), "Orders by #{contact.business}"]
    end
  end

  def contact_business
    contact&.business
  end

  def contact_business=(business)
    self.contact = Contact.find_by_business(business) if business.present?
  end

  def fulfilled?
    fulfilled_on != nil
  end

  def fulfill
    self.fulfilled_on = Date.today
  end

  def unfulfill
    self.fulfilled_on = nil
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :logged_in_as_admin?

  def index
    @invoices       = xero.Invoice.all if Rails.env.production? || testing_xero
    @orders, @title = Order.display_all(params[:show] || 'active')

    respond_to do |format|
      format.html
    end
  end

  def invoice
    # @order        = Order.find(params[:id])
    # rails_contact = @order.contact
    # if Rails.env.production? || testing_xero
    # xero_contact = XeroFindOrCreateContact.new(rails_contact.business)
    #
    # invoice = XeroCreateInvoice.new(xero_contact, @order.customer_po)
    #
    # if @order.line_items.empty?
    #   flash[:notice] = 'Please create some Line Items.  Your invoice was NOT saved.'
    #   redirect_to admin_order_path(@order)
    #   return
    # end
    #
    # @order.line_items.each do |line_item|
    #   if line_item.product.nil?
    #     flash[:notice] = 'Please select a cheese in your Line Items.  Your invoice was NOT saved.'
    #     redirect_to admin_order_path(@order)
    #   end
    #   invoice.add_line_item(
    #     item_code: line_item.product.xero_item_code,
    #     description: line_item.units.to_s + 'x ' + line_item.size + ' ' + line_item.product.name,
    #     quantity: 1,
    #     account_code: LineItem::ACCOUNT_CODES[line_item.size],
    #     unit_amount: rails_contact.price_point
    #   )
    # end
    #
    # if invoice.save
    #   flash[:notice]    = 'A new invoice was created in Xero'
    #   @order.invoice_id = invoice.invoice_id
    #   @order.save
    # else
    #   flash[:notice] = "#{invoice.inspect}An error occurred.  Your invoice was NOT saved."
    # end
    # end

    flash[:notice] = 'Xero integration disabled. Your invoice was NOT saved.'
    redirect_to admin_order_path(@order)
  end

  def fulfill
    @order = Order.find(params[:id])
    @order.fulfill

    respond_to do |format|
      if @order.save
        format.html do
          redirect_to admin_orders_path,
                      notice: 'Order was successfully delivered. <br /><br />' +
                              "<a href=\"/admin/orders/#{@order.id}\">View Order</a>".html_safe
        end
      else
        format.html { redirect_to admin_orders_path, notice: 'Error' }
      end
    end
  end

  def unfulfill
    @order = Order.find(params[:id])
    @order.unfulfill

    respond_to do |format|
      if @order.save
        format.html { redirect_to edit_admin_order_path(@order), notice: 'Order was successfully undelivered.' }
      else
        format.html { redirect_to admin_order_path(@order), notice: 'Error' }
      end
    end
  end

  def show
    @order   = Order.find(params[:id])
    @invoice = xero.Invoice.find(@order.invoice_id) if @order.invoice_id

    redirect_to(edit_admin_order_path(@order.id)) if @order.fulfilled_on.nil? && @order.invoice_id.nil?
  end

  def new
    @order            = Order.new
    @contact_business = params[:contact]

    respond_to do |format|
      format.html
    end
  end

  def edit
    @order   = Order.find(params[:id])
    @invoice = xero.Invoice.find(@order.invoice_id) if @order.invoice_id

    redirect_to(admin_order_path(@order.id)) if @order.fulfilled_on || @order.invoice_id
  end

  def create
    @order            = Order.create(order_params)
    @order.created_by = current_user
    @order.updated_by = current_user

    respond_to do |format|
      if @order.save
        OrderMailer.new_order(@order).deliver_now
        format.html do
          redirect_to edit_admin_order_path(@order),
                      notice: 'Order was successfully created. <br /><br />' +
                              ' <a href="/admin/orders/new">Add Another Order</a>'.html_safe
        end
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    @order            = Order.find(params[:id])
    @order.updated_by = current_user
    xero_invoice      = nil
    # xero_invoice      = xero.Invoice.first(where: { invoice_id: @order.invoice_id }) if xero
    path              = params[:save] ? admin_orders_url : edit_admin_order_url(@order)

    params[:order][:invoice_id] = nil if xero_invoice.nil?
    respond_to do |format|
      if @order.update!(order_params)
        OrderMailer.updated_order(@order).deliver_now
        format.html { redirect_to path, notice: 'Order was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to admin_orders_url }
    end
  end

  private

  def order_params
    params.require(:order).permit(
      :contact_business, :delivery_date, :distribution_center_id, :customer_po, :invoice_id, :comments, :created_by_id,
      :updated_by_id, line_items_attributes: [:fulfilled, :units, :size, :product_id, :id, :_destroy]
    )
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def index; end
end

app/controllers/user/orders_controller.rb
class User::OrdersController < ApplicationController
  before_action :logged_in?
  before_action :only_access_self

  def index
    if current_user.contact
      @orders, @title = Order.display(current_user.contact.orders, params[:show] || 'active')
    else
      @orders = nil
      @title  = 'Your account has not been set up'
    end

    respond_to do |format|
      format.html
    end
  end

  def show
    @order = Order.find(params[:id])

    redirect_to edit_user_order_path(@order) unless @order.fulfilled_on
  end

  def new
    @order            = Order.new
    @contact_business = current_user.contact.business

    respond_to do |format|
      format.html
    end
  end

  def edit
    @order   = Order.find(params[:id])
    @invoice = xero.Invoice.find(@order.invoice_id) if @order.invoice_id
  end

  def create
    @order            = Order.create(order_params)
    @order.created_by = current_user
    @order.updated_by = current_user

    respond_to do |format|
      if @order.save
        OrderMailer.new_order(@order).deliver_now
        format.html do
          redirect_to edit_user_order_path(@order),
                      notice: 'Order was successfully created. <br /><br /> ' +
                              '<a href="/user/orders/new">Add Another Order</a>'.html_safe
        end
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    @order                      = Order.find(params[:id])
    @order.updated_by           = current_user
    xero_invoice                = nil
    # xero_invoice                = xero.Invoice.first(where: { invoice_id: @order.invoice_id }) if xero
    params[:order][:invoice_id] = nil if xero_invoice.nil?
    path                        = params[:save] ? user_orders_url : edit_user_order_url(@order)

    respond_to do |format|
      if @order.update!(order_params)
        OrderMailer.updated_order(@order).deliver_now
        format.html { redirect_to path, notice: 'Order was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to user_orders_url }
    end
  end

  private

  def order_params
    params.require(:order).permit(
      :contact_business,
      :delivery_date,
      :distribution_center_id,
      :customer_po,
      :invoice_id,
      :comments,
      :created_by_id,
      :updated_by_id,
      line_items_attributes: [:fulfilled, :units, :size, :age, :product_id, :id, :_destroy]
    )
  end

  def only_access_self
    return unless params[:id]

    order = Order.find_by_id(params[:id])
    if order.contact
      redirect_to user_orders_path unless order.contact.user == current_user
    else
      redirect_to user_orders_path
    end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def xero_invoice_link
    'https://go.xero.com/AccountsReceivable/Edit.aspx?InvoiceID='
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_calculator.html.erb
<legend>
  Retail Price Calculator
</legend>

<div id="calculator">
  <span id="price_per_ounce" style="display:none;"><%= contact.price_per_ounce %></span>
  <p>
    <label for="ounces">Ounces</label>
    <input id="ounces" type="number" , size="4" , step="any" onfocus="this.select();" onmouseup="return false;" onkeyup="calculate()"/>
  </p>
  <p>
    <span>Retail Price: </span>
    <strong><span id="retail_price">0.00</span></strong>
  </p>
</div>

<script>
    function calculate() {
        let price_per_ounce = document.getElementById("price_per_ounce").innerHTML;
        let ounces = document.getElementById("ounces");
        let retail_price_span = document.getElementById("retail_price");

        let retail_price = Math.round((price_per_ounce * ounces.value) * 100) / 100;
        let retail_string = retail_price + '';
        length = (retail_string).replace('.', '').length;

        if (retail_string.indexOf(".") === -1) {
            retail_string += ".00";
        } else if (length === 2 && retail_string.indexOf(".") !== -1) {
            retail_string += "0";
        }

        retail_price_span.innerHTML = retail_string;
    }
</script>

app/views/admin/orders/_contact.html.erb
<legend>
  <%= link_to contact.business, edit_admin_contact_path(contact) %>
</legend>

<div style="float:right;">
  <%= link_to "View all orders by #{contact.business}", admin_orders_path({show: contact.id}) %>
</div>

<p>
  Contact: <strong><%= contact.name %></strong>
</p>

<p>
  Paperless Billing: <strong>
  <% if contact.paperless_billing -%>
    Yes
  <% else -%>
    No
  <% end -%>
</strong>
</p>

<% if contact.phone -%>
  <p>
    Phone: <strong><%= contact.phone %></strong>
  </p>
<% end -%>

<% if contact.email -%>
  <p>
    Email: <strong><%= link_to contact.email, "mailto:" + contact.email, target: "_blank" %></strong>
  </p>
<% end -%>

<p>
  Wholesale Price Point: <strong><%= contact.price_point %></strong>
</p>

<% if contact.mark_retail -%>
  <p>
    Retail Price per ounce: <strong><%= contact.price_per_ounce %></strong>
  </p>
<% end -%>

<p>
  Distributor: <strong><%= contact.distribution_center.name %></strong>
</p>

<p>
  Address: <strong><%= contact.address %></strong>
</p>

<p>
  <%= contact.comments %>
</p>

app/views/admin/orders/_form.html.erb
<% if @order.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

    <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :contact_business %>

  <% if @contact_business -%>
    <%= f.text_field :contact_business,
                     value: @contact_business,
                     data: {autocomplete_source: Contact.order(:business).map(&:business)}
    %>
  <% else -%>
    <%= f.text_field :contact_business, data: {autocomplete_source: Contact.order(:business).map(&:business)} %>
  <% end -%>
</div>

<div class="field">
  <%= f.label :delivery_date %>

  <% if @order.delivery_date -%>
    <%= f.text_field :delivery_date, class: "datepicker", value: @order.delivery_date.strftime("%d-%m-%Y") %>
  <% else -%>
    <%= f.text_field :delivery_date, class: "datepicker" %>
  <% end -%>
</div>

<div class="field">
  <%= f.label :customer_po, "Customer PO" %>
  <%= f.text_field :customer_po %>
</div>

<h3>Line Items</h3>

<div id="line_items">
  <%= f.fields_for :line_items do |line_item| %>
    <%= render 'line_item_fields', f: line_item %>
  <% end -%>
  <div class="links">
    <%= link_to_add_association 'add line item', f, :line_items %>
  </div>
</div>

<div class="field">
  <%= f.label :comments %><br/>
  <%= f.text_area :comments, rows: 15, cols: 50 %>
</div>

app/views/admin/orders/_line_item_fields.html.erb
<div class="nested-fields">
  <span class="field">
    <%= f.check_box :fulfilled %>
    <% f.label :fulfilled %>
  </span>
  <span class="field">
    <% f.label :units %>
    <%= f.number_field :units, step: 'any', class: "li_units", size: 4 %>
  </span>
  <span class="field">
    <% f.label :size %>
    <%= f.select(:size, LineItem::SIZES) %>
  </span>
  <span class="field">
    <% f.label :product_id %>
    <%= f.collection_select(:product_id,
                            Product.where(in_production: true).order("name ASC"),
                            :id,
                            :name,
                            {prompt: "Select Cheese"})
    %>
  </span>

  <span>  
    <%= link_to_remove_association "X", f %>
  </span>
</div>

app/views/admin/orders/_order_table.html.erb
<tr class="<%= cycle "even", "odd" %>">
  <td><strong><%= order.id.to_s %></strong></td>
  <td>
    <% if order.customer_po -%>
      <%= order.customer_po.truncate(15) %>
    <% else -%>
      &nbsp;
    <% end -%>
  </td>
  <% if @show == "fulfilled" || order.invoice_id -%>
    <td><%= link_to order.contact.business, admin_order_path(order) %></td>
  <% else -%>
    <td><%= link_to order.contact.business, edit_admin_order_path(order) %></td>
  <% end -%>
  <td class=<%= order.delivery_date < Date.today && !order.fulfilled? ? 'late' : '' %>>
    <% if @show == "fulfilled" -%>
      <%= humanize_date order.fulfilled_on %>
    <% else -%>
      <%= humanize_date order.delivery_date %>
    <% end -%>
  </td>
  <td>
    <% if order.invoice_id && @invoices -%>
      <% invoice = @invoices.detect { |i| i.invoice_id == order.invoice_id } -%>
      <% text = invoice.status -%>
      <% if invoice.sent_to_contact -%>
        <% text += " & Sent" -%>
      <% end -%>
      <%= link_to text, xero_invoice_link + order.invoice_id, target: "_blank" %>
    <% else -%>
      NONE
    <% end -%>
  </td>
  <% if order.fulfilled? -%>
    <td></td>
    <td></td>
  <% else -%>
    <td><%= link_to 'Deliver', fulfill_admin_order_path(order), id: "deliver_#{order.id}" %></td>
    <td>
      <%= link_to 'Void', admin_order_path(order), confirm: 'Are you sure?', method: :delete, id: "void_#{order.id}" %>
    </td>
  <% end -%>
</tr>

app/views/admin/orders/_table_head.html.erb
<tr class="title">
  <th>PO</th>
  <th>Cust PO</th>
  <th>Business</th>
  <th>
    <% if @show == "fulfilled" -%>
      Fulfilled On
    <% else -%>
      Delivery Date
    <% end -%>
  </th>
  <th>Invoice Status</th>
  <th></th>
  <th></th>
</tr>

app/views/admin/orders/edit.html.erb
<h1>PO <%= @order.id %></h1>

<p>
  Created by <%= @order.created_by.name %> on <%= humanize_date @order.created_at %>.
  <% if @order.updated_by -%>
    <br/>
    Updated by <%= @order.updated_by.name %> on <%= humanize_date @order.updated_at %>.
  <% end -%>
</p>

<%= form_for(@order, url: admin_order_path(@order)) do |f| %>

  <p>
    <% if @order.invoice_id -%>
    <h4>
      Xero Invoice Status: <%= @invoice.status %>
      <% if @invoice.sent_to_contact -%>
        & Sent
      <% end -%>
    </h4>
    <%= link_to 'Open Invoice', xero_invoice_link + @order.invoice_id, target: "_blank" %>
  <% else -%>
    <%= link_to 'Create Invoice', invoice_admin_order_path(@order) %>
    <div class="field">
      <%= f.label :invoice_id, "Existing Xero Invoice ID" %>
      <%= f.text_field :invoice_id %>
    </div>
  <% end -%>
  </p>

  <p>
    <%= link_to 'Mark Delivered', fulfill_admin_order_path(@order) %> |
    <%= link_to 'Void', admin_order_path(@order), confirm: 'Are you sure?', method: :delete %>
  </p>


  <p class="actions">
    <%= f.submit 'Update', name: :update, disable_with: "Loading..." %>
    <%= f.submit 'Save & Finish', name: :save, disable_with: "Loading..." %>
    <%= link_to 'Cancel', admin_orders_path %>
  </p>



  <fieldset class="column">
    <legend>Order <%= @order.id %></legend>
    <%= render partial: 'form', locals: {f: f} %>

    <p class="actions">
      <%= f.submit 'Update', name: :update, disable_with: "Loading..." %>
      <%= f.submit 'Save & Finish', name: :save, disable_with: "Loading..." %>
      <%= link_to 'Cancel', admin_orders_path %>
    </p>
  </fieldset>
<% end -%>

<fieldset class="column">
  <%= render partial: 'contact', locals: {contact: @order.contact} %>
</fieldset>

<% if @order.contact.mark_retail -%>
  <fieldset class="column">
    <%= render partial: 'calculator', locals: {contact: @order.contact} %>
  </fieldset>
<% end -%>

app/views/admin/orders/index.html.erb
<h1><%= @title %></h1>

<p>
  <%= link_to 'New Order', new_admin_order_path %>
</p>

<p>
  <%= link_to 'Active Orders', admin_orders_path({show: "active"}) %> |
  <%= link_to 'Delivered Orders', admin_orders_path({show: "fulfilled"}) %> |
  <%= link_to 'Late Orders', admin_orders_path({show: "late"}) %>
</p>

<div class="wide_wrapper">
  <table class="crud">
    <%= render "table_head" %>
    <% @orders.each do |order| -%>
      <%= render "order_table", order: order %>
    <% end -%>
  </table>
</div>

<br/>

app/views/admin/orders/new.html.erb
<h1>New order</h1>

<%= form_for(@order, url: admin_orders_path) do |f| -%>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit 'Save', name: :save, disable_with: "Loading..." %>
<% end -%>

<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/show.html.erb
<h1><%= @order.contact.business %></h1>

<p>
  Created by <%= @order.created_by.name %> on <%= humanize_date @order.created_at %>.
  <% if @order.updated_by -%>
    <br/>
    Updated by <%= @order.updated_by.name %> on <%= humanize_date @order.updated_at %>.
  <% end -%>
</p>

<p>
  <% if @order.invoice_id -%>
  <h4>
    Xero Invoice Status: <%= @invoice.status %>
    <% if @invoice.sent_to_contact -%>
      & Sent
    <% end -%>
  </h4>
  <%= link_to 'Open Invoice', xero_invoice_link + @order.invoice_id, target: "_blank" %>
<% end %>
</p>

<% if @order.fulfilled_on -%>
  <h2>Delivered on <%= humanize_date @order.fulfilled_on %></h2>
  <p>
    <%= link_to 'Undeliver', unfulfill_admin_order_path(@order) %>
  </p>
<% else -%>
  <p>
    <%= link_to 'Mark Delivered', fulfill_admin_order_path(@order) %> |
    <%= link_to 'Void', admin_order_path(@order), confirm: 'Are you sure?', method: :delete %>
  </p>
<% end %>

<fieldset class="column">
  <legend>Order #<%= @order.id %></legend>

  <table class="crud">
    <tr class="title">
      <th>Quantity</th>
      <th>Size</th>
      <th>Cheese</th>
    </tr>

    <% @order.line_items.each do |line_item| -%>
      <tr class="<%= cycle "even", "odd" %>">
        <td style="white-space: nowrap"><%= line_item.units %></td>
        <td style="white-space: nowrap"><%= line_item.size %></td>
        <td style="white-space: nowrap"><%= line_item.product.name %></td>

      </tr>

    <% end -%>
  </table>

  <p><%= @order.comments %></p>
</fieldset>

<fieldset class="column">
  <%= render partial: 'contact', locals: {contact: @order.contact} %>
</fieldset>

<% if @order.contact.mark_retail -%>
  <fieldset class="column">
    <%= render partial: 'calculator', locals: {contact: @order.contact} %>
  </fieldset>
<% end -%>