config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root to: 'home#index'

  get 'press', to: 'press#index'
  get 'tr', to: 'tr#index'
  get 'admin', to: 'admin#index'
  get 'employment', to: 'employment#index'
  get 'order', to: 'order#index'
  get 'blog', to: 'blog#index'

  get '/payment', to: redirect('http://tinyurl.com/cheese-invoice')

  get 'logout',
      controller: 'sessions',
      action: 'destroy'

  match 'login', via: [:get, :post],
                 controller: 'sessions',
                 action: 'new'

  %w[404 422 500].each do |code|
    get code, to: 'errors#show', code: code
  end

  resources :articles
  resources :sessions
  resources :products
  resources :accounts

  namespace :user do
    resources :orders
    resources :contacts
    resources :users
  end

  namespace :admin do
    get 'fulfillment', to: 'fulfillment#index'
    resources :salespeople
    resources :states
    resources :towns
    resources :distributors
    resources :distribution_centers
    resources :trade_items
    resources :users do
      member do
        get 'undestroy'
      end
    end
    resources :articles
    resources :products
    resources :notes
    resources :reports do
      collection do
        get 'sales_activity'
      end
    end
    resources :contacts do
      member do
        get 'undestroy'
        get 'repeat_last_order'
      end
    end
    resources :orders do
      member do
        get 'fulfill'
        get 'unfulfill'
        get 'invoice'
        get 'update_invoice'
      end
    end
  end
end

app/models/town.rb
class Town < ActiveRecord::Base
  has_many :contacts
  belongs_to :state

  def full_name
    name + ', ' + state.name
  end
end

app/controllers/admin/towns_controller.rb
class Admin::TownsController < ApplicationController
  before_action :logged_in_as_admin?
  before_action :set_town, only: [:show, :edit, :update, :destroy]

  def index
    @towns = Town.all
  end

  def show; end

  def new
    @town = Town.new
  end

  def edit; end

  def create
    @town = Town.new(town_params)

    if @town.save
      redirect_to admin_towns_path, notice: 'Town was successfully created.'
    else
      render :new
    end
  end

  def update
    if @town.update(town_params)
      redirect_to edit_admin_town_path(@town), notice: 'Town was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @town.destroy
    redirect_to admin_towns_url, notice: 'Town was successfully destroyed.'
  end

  private

  def town_params
    params.require(:town).permit(:state_id, :name)
  end
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/views/admin/towns/_form.html.erb
<div class="field">
  <%= f.label :name %><br/>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :state %><br/>
  <%= f.select(:state_id, State.all.collect { |t| [t.name, t.id] }) %><br/>
</div>

<div class="actions">
  <%= f.submit disable_with: "Loading..." %>
</div>

app/views/admin/towns/edit.html.erb
<h1>Editing Town</h1>

<%= form_for(@town, url: admin_towns_path(@town)) do |f| -%>
  <%= render partial: 'form', locals: {f: f} %>
<% end -%>

app/views/admin/towns/index.html.erb
<h1>Listing Towns</h1>

<table class="crud">
  <tr class="title">
    <th>Name</th>
    <th>State</th>
    <th></th>
  </tr>

  <% @towns.each do |town| %>
    <tr class="<%= cycle "even", "odd" %>">
      <td><%= link_to town.name, edit_admin_town_path(town) %></td>
      <td><%= town.state.name %></td>
      <td><%= link_to 'X', admin_town_path(town), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Town', new_admin_town_path %><br/>
<%= link_to 'New State', new_admin_state_path %>

app/views/admin/towns/new.html.erb
<h1>New Town</h1>

<%= form_for(@town, url: admin_towns_path) do |f| -%>
  <%= render partial: 'form', locals: {f: f} %>
<% end -%>