config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root to: 'home#index'

  get 'press', to: 'press#index'
  get 'tr', to: 'tr#index'
  get 'admin', to: 'admin#index'
  get 'employment', to: 'employment#index'
  get 'order', to: 'order#index'
  get 'blog', to: 'blog#index'

  get '/payment', to: redirect('http://tinyurl.com/cheese-invoice')

  get 'logout',
      controller: 'sessions',
      action: 'destroy'

  match 'login', via: [:get, :post],
                 controller: 'sessions',
                 action: 'new'

  %w[404 422 500].each do |code|
    get code, to: 'errors#show', code: code
  end

  resources :articles
  resources :sessions
  resources :products
  resources :accounts

  namespace :user do
    resources :orders
    resources :contacts
    resources :users
  end

  namespace :admin do
    get 'fulfillment', to: 'fulfillment#index'
    resources :salespeople
    resources :states
    resources :towns
    resources :distributors
    resources :distribution_centers
    resources :trade_items
    resources :users do
      member do
        get 'undestroy'
      end
    end
    resources :articles
    resources :products
    resources :notes
    resources :reports do
      collection do
        get 'sales_activity'
      end
    end
    resources :contacts do
      member do
        get 'undestroy'
        get 'repeat_last_order'
      end
    end
    resources :orders do
      member do
        get 'fulfill'
        get 'unfulfill'
        get 'invoice'
        get 'update_invoice'
      end
    end
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  validates_presence_of :report_type, :name

  validates :name, uniqueness: true

  REPORT_TYPES = [
    'Orders by Item',
    'Orders by Account',
    'Orders by Salesperson'
  ].freeze
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  def index
    @reports = Report.all
  end

  def show; end

  def new
    @report = Report.new
  end

  def edit; end

  def create
    @report = Report.new(report_params)

    if @report.save
      redirect_to admin_report_path(@report), notice: 'Report was successfully created.'
    else
      render :new
    end
  end

  def update
    if @report.update(report_params)
      redirect_to admin_report_path(@report), notice: 'Report was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @report.destroy
    redirect_to admin_reports_url, notice: 'Report was successfully destroyed.'
  end

  def sales_activity
    ReportsMailer.sales_activity.deliver_now
    redirect_to admin_url, notice: 'Sales Activity has been emailed to admins.'
  end

  private

  def set_report
    @report = Report.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:report_type, :start_date, :end_date, :totals?, :name, :last_run)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/admin/reports/_form.html.erb
<% if @report.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

    <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="column">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :report_type %>
    <%= select(:report, :report_type, Report::REPORT_TYPES) %>
  </div>

  <div class="field">
    <%= f.check_box :totals? %>
    <%= f.label :totals?, "Show only total numbers" %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <% if @report.start_date -%>
      <%= f.text_field :start_date, class: "datepicker", value: @report.start_date.strftime("%d-%m-%Y") %>
    <% else -%>
      <%= f.text_field :start_date, class: "datepicker" %>
    <% end -%>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <% if @report.end_date -%>
      <%= f.text_field :end_date, class: "datepicker", value: @report.end_date.strftime("%d-%m-%Y") %>
    <% else -%>
      <%= f.text_field :end_date, class: "datepicker" %>
    <% end -%>
  </div>

  <div class="actions">
    <%= f.submit disable_with: "Loading..." %> |
    <%= link_to 'Back', admin_reports_path %>
  </div>
</div>

app/views/admin/reports/edit.html.erb
<h1>Editing Report</h1>

<%= form_for(@report, url: admin_report_path(@report)) do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
<% end -%>

app/views/admin/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reports</h1>

<table>
  <thead>
  <tr>
    <th>Report type</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Totals?</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @reports.each do |report| %>
    <tr>
      <td><%= report.report_type %></td>
      <td><%= report.start_date %></td>
      <td><%= report.end_date %></td>
      <td><%= report.totals? %></td>
      <td><%= link_to 'Show', admin_report_path(report) %></td>
      <td><%= link_to 'Edit', edit_admin_report_path(report) %></td>
      <td>
        <%= link_to 'X',
                    admin_report_path(report),
                    confirm: 'Are you sure?',
                    method: :delete,
                    id: "delete_#{report.id}" %>
        &nbsp;
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New Report', new_admin_report_path %>

app/views/admin/reports/new.html.erb
<h1>New Report</h1>

<%= form_for(@report, url: admin_reports_path) do |f| -%>
  <%= render partial: 'form', locals: {f: f} %>
<% end -%>

app/views/admin/reports/show.html.erb
<h1><%= @report.name %></h1>

<p>
  <%= link_to 'Edit Report', edit_admin_report_path(@report) %>
</p>

<p>
  <strong>Report type:</strong>
  <%= @report.report_type %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @report.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @report.end_date %>
</p>

<p>
  <strong>Totals?:</strong>
  <%= @report.totals? %>
</p>